# Circle tracking task with end-effector constraints


# MPC & sim parameters
ctrl_freq: 100         # Control frequency
RICCATI: False 


# OCP 
dt: 0.0125                                             # OCP integration step 
N_h: 40                                              # Horizon length in nodes
maxiter: 100                                           # Max number of iterations 
solver_termination_tolerance: 0.0001              # Tolerance on KKT residual 
q0: [0.0000, 0.0000, 0.2980, 
     0.0000, 0.0000, 0.0000, 1.0000, 
     0.0000, 0.9000, -1.8000, 
     0.0000, 0.9000, -1.8000, 
     0.0000, 0.9000, -1.8000, 
     0.0000, 0.9000, -1.8000]

dq0: [0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0,
      0.0, 0.0, 0.0]

T_total: 10.0

# CSSQP solver parameters
SOLVER: 'CSQP'
with_callbacks: True
use_filter_line_search: False
warm_start: True
max_qp_iter: 500    #125 
qp_termination_tol_abs: 0.00001
qp_termination_tol_rel: 0.00001
warm_start_y: False 
reset_rho: False


# Constraints terms
# to select from the list : 'stateBox', 'ctrlBox', 'translationBox', 'None'
WHICH_CONSTRAINTS: ['ctrlBox']

ctrlLimit: [23.7, 23.7, 45.43,
            23.7, 23.7, 45.43,
            23.7, 23.7, 45.43,
            23.7, 23.7, 45.43]

# Cost function terms
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['stateReg', 'ctrlReg', 'footClearance'] 


footClearanceWeight: 10.0
footClearanceWeightTerminal: 10.0
footClearanceSigmoidSteepness: -30.0

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [100, 100, 100,
                  1.0, 1.0, 1.0,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                  1.0, 1.0, 1.0,
                  1.0, 1.0, 1.0,
                  0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
stateRegWeightsTerminal: [1000.0, 1000.0, 1000.0,
                        10.0, 10.0, 10.0,
                        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                        0.0, 0.0, 0.0,
                        1.0, 1.0, 1.0, 
                        0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
stateRegWeight: 10.0
stateRegWeightTerminal: 10.0

stateRegRef: [0.5, 0.0000, 0.2700, 
              0.0000, 0.0000, 0.0000, 1.0000, 
              0.0000, 0.9000, -1.8000, 
              0.0000, 0.9000, -1.8000, 
              0.0000, 0.9000, -1.8000, 
              0.0000, 0.9000, -1.8000,
              1.0000, 0.0000, 0.0000,
              0.0000, 0.0000, 0.0000,
              0.0000, 0.0000, 0.0000,
              0.0000, 0.0000, 0.0000,
              0.0000, 0.0000, 0.0000,
              0.0000, 0.0000, 0.0000]


 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegWeights: [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]
ctrlRegWeight: 0.001

# armature
armature: [0., 0., 0., 0., 0., 0., 0.]

contactFrameNames: ["FL_foot", "FR_foot", "RL_foot", "RR_foot"],